### ISSUE TITLE
Suggestion: add a little info menu!

### ISSUE THREAD

**Issue by Hussseinkizz** [lewhunt/react-tv-player#13]
Also can you add a little wiki or help icon that can open up a modal popup menu that informs a user of possible keys and functionality? yes the UI is intuitive enough and the GitHub docs but it would be helpful addon too for end users who end up using the player!

**Comment by lewhunt** [comment]
Hi, thanks for the suggestion.

Currently I don't intend to do this as part of the core component because there is already the flexibility to add custom buttons. The developer can add an info menu or help popup via a custom button action along with a descriptive label (see readme https://github.com/lewhunt/react-tv-player?tab=readme-ov-file#custom-buttons).
