### ISSUE TITLE
Can show quality list?

### ISSUE THREAD

**Issue by AmirKaftari** [lewhunt/react-tv-player#15]
Hi.
this library can detect qualities from m3u8 and set buttons for that ?

**Comment by lewhunt** [comment]
Hi,

Not out of the box, but you should be able to add code in order to achieve this:

Under the hood it's using hls.js from the react player for m3u8 hls files. Take a look at this for reference for accessing quality levels: https://github.com/cookpete/react-player/issues/523#issuecomment-442652418

In order to add a list, you could add a [custom button ](https://github.com/lewhunt/react-tv-player?tab=readme-ov-file#custom-buttons)to the player, which could then in turn display a list or [menu](https://github.com/lewhunt/react-tv-player/issues/13).

Hope that helps!
