### ISSUE TITLE
React Native: Unable to resolve "react-tv-player" from [Page.tsx]

### ISSUE THREAD

**Issue by amingsttc** [lewhunt/react-tv-player#19]
So, I stumbled across this package a few hours ago and it literally is exactly what I am looking for in terms of a functional player with a custom UI that supports youtube  videos. Unfortunately, I think that because it is a React package, using it in Expo and ReactNative can't work but I wanted to check here first.

Is there any way I can use this package inside of ReactNative?

**Comment by lewhunt** [comment]
Hey, thanks for taking a look.

Yes unfortunately you suspected right, this library component is designed for React (web) and relies on HTML elements like video and iframe, which are not available in React Native.

Have you tried looking at React Native video libraries? [react-native-video](https://www.npmjs.com/package/react-native-video) looks promising, and [react-native-youtube-iframe](https://www.npmjs.com/package/react-native-youtube-iframe) for youtube urls.

Alternatively, if you really want to use this repo in react native, you could consider loading it inside a react native webview, but it may introduce performance limitations and won't use native controls.

Hope this helps!

**Comment by amingsttc** [comment]
So currently that is my solution, that is using react-native-youtube-iframe, for playing youtube videos but the user experience isn't great on tvos and I can't figure out how to customize that player in any way. If I may ask, how does it support Android and iOS if there isn't a native layer for it?

My other thought wwas to use it in a react native webview and make custom controls but I am not that concerned about using native components for this.

**Comment by lewhunt** [comment]
Hi,

This player component supports TV web apps, not native tvOS or Android apps. Here's a snippet from the readme in case you skipped the enthralling read!

> **Broad Device Support**
> From Amazon Fire TV, LG webOS and Samsung Tizen Smart TVs to Xbox consoles and desktop web browsers, ReactTVPlayer covers most big-screen devices running web apps with post-2017 Chromium browsers.

If you want to get YouTube working in tvOS apps and react-native-youtube-iframe isn't cutting it, might be worth taking a look at the [iOS YouTube helper library ](https://developers.google.com/youtube/v3/guides/ios_youtube_helper)but I don't know how it works I'm afraid.

As a last resort, yes you could try this component in a react native webview, but I'm not familiar with how you do that. This is how I've got it working in a codepen web page so that might help you get started: https://codepen.io/lewhunt/pen/dyLOQVg

Good luck, let me know how you get on.
