### ISSUE TITLE
Video Error Issue

### ISSUE THREAD

**Issue by ghost** [lewhunt/react-tv-player#21]
I am trying to use use onError but its not working for me

**Comment by lewhunt** [comment]
Hi,

The onError callback prop will be passed back from the underlying ReactPlayer component when it fails to play media.

I've updated the sample demo app to show how onError can be used. Code snippet below also for reference:

```
const App = () => {

  // intentionally changed to an invalid 'tears-of-metal' manifest url so that an error gets raised
  const url = "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-metal.ism/.m3u8";
  
  // Called when an error occurs whilst attempting to play media
  const handleError = (
    error,
    data,
    hlsInstance,
    hlsGlobal
  ) => {
    console.log("error: ", error);
    console.log("data (optional): ", data);
    console.log("hlsInstance (optional): ", hlsInstance);
    console.log("hlsGlobal (optional): ", hlsGlobal);
  };
  
  return <TVPlayer url={url} onError={handleError}  />;
}
```

**Comment by ghost** [comment]
Great, It works for me.
Can we add Error thumbnil or a Error poster when it gives us error in TVPlayer or we need to create a new view to show Error Poster.

One more thing some times we get error but after few seconds its play so How can we handle this error Poster.

I am creating a tv application,Live channel are working fine but when I going for catch up tv section videos are not playing , I tried in VLC its working there.

**Comment by lewhunt** [comment]
It's generally advisable to create an error poster/dialog component as part of your app rather than directly inside the player library. Use the callback to set some state, then you can trigger your error to display.

If it sometimes takes a few seconds to play, you could delay the handleError check with a setTimeout.

Strange that live is working for you but not catchup. My example is using catchup hls and dash videos ok. Are you definitely using a custom url rather than a local video source? The video needs to be hosted. Maybe try the underlying React Player demo here: https://cookpete.github.io/react-player/
